### ISSUE TITLE
[Feature request] Switch from checking for events every few hours to using webhooks

### ISSUE THREAD

**Issue by SVijayB** [SVijayB/OSC-DBot#20]
### About
Switch from pinging the API every few hours to creating a webhook that sends a message to the server's announcement channel upon event creation. 
Modifying OSC-API to send a ping/request to a web server hosted along with the bot and then using it to send out an announcement would be the method to do this.
For more information, click [here](https://stackoverflow.com/questions/48693069/running-flask-a-discord-bot-in-the-same-application)

### Why?
This allows the API to idle and prevents it from exhausting the 550 free dyno hours provided by Heroku.
It's also a lot more efficient.

**Comment by officialakhil** [comment]
Hey there! In my opinion, there is no need for a web server alongside the discord bot running. Discord has webhooks built in that let you send a message. 

Refer https://discord.com/developers/docs/resources/webhook#webhook-resource 

A python library: https://pypi.org/project/dhooks/

```py
from dhooks import Webhook, Embed

hook = Webhook('url')

embed = Embed(
    description='This is the **description** of the embed! :smiley:',
    color=0x5CDBF0,
    timestamp='now'  # sets the timestamp to current time
    )

image1 = 'https://i.imgur.com/rdm3W9t.png'
image2 = 'https://i.imgur.com/f1LOr4q.png'

embed.set_author(name='Author Goes Here', icon_url=image1)
embed.add_field(name='Test Field', value='Value of the field :open_mouth:')
embed.add_field(name='Another Field', value='1234 :smile:')
embed.set_footer(text='Here is my footer text', icon_url=image1)

embed.set_thumbnail(image1)
embed.set_image(image2)

hook.send(embed=embed)
```

Creating webhooks: (Channel settings > Integrations)
![image](https://user-images.githubusercontent.com/43880032/145167048-a13a9a2c-13e5-49f9-8129-1c4d6b122418.png)

And I think it makes the most sense to add this change to https://github.com/Open-Source-Community-VIT-AP/OSC-API and thus move this issue over there and completely remove announcements logic from the discord bot.

**Comment by SVijayB** [comment]
Hey @officialakhil, That makes a lot more sense, Utilizing existing discord webhooks would indeed make this a lot easier. Thanks for bringing that to notice! 
Closing issue, will open another in the OSC-API.
